services:
  gui:
    image: dpage/pgadmin4:${GUI_TAG:-8.4}
    restart: unless-stopped
    ports:
      - ${GUI_PORT:-80}:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${GUI_USER:-admin@example.org}
      PGADMIN_DEFAULT_PASSWORD: ${GUI_PASSWORD:-password}
    volumes:
      - vol-pgadmin:/var/lib/pgadmin
      - ./scripts/:/scripts
    networks:
      - backend

networks:
  backend:
    external: true

volumes:
  vol-pgadmin: